# This is a basic workflow to help you get started with Actions

name: hello-github-actions

# Controls when the workflow will run
on:
  workflow_dispatch:
    inputs:
      json:
        type: string

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  job2:
    runs-on: ubuntu-latest
    steps:
      - name: Parse JSON
        id: parse_json
        run: |
          echo "${{ github.event.inputs.json }}" > json_data.json
          echo "::set-output name=filename::json_data.json"

      - name: Iterate over JSON
        id: iterate_json
        run: |

          source_repo=($(echo $json | jq -r '.[].source_repo'))
          tag=($(echo $json | jq -r '.[].tag'))

          for ((i=0; i<${#source_repo[@]}; i++)); do
            echo "source_repo: ${source_repo[i]}, tag: ${tag[i]}"
          done
        
