# This is a basic workflow to help you get started with Actions

name: hello-github-actions

# Controls when the workflow will run
on:
  workflow_dispatch:
    inputs:
      json:
        type: string

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  job2:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - id: parse_json
        run: |
          echo "${{ github.event.inputs.json }}" > json_data.json
          echo "::set-output name=filename::json_data.json"

      - name: Iterate over JSON
        id: iterate_json
        run: |

          const jsonStr = '${{ inputs.json }}';

          // 解析 JSON 字符串为 JavaScript 对象
          const jsonObj = JSON.parse(jsonStr);
          console.log(jsonObj);
          // 遍历 JSON 对象
          for (const key in jsonObj) {
            console.log(`${key}: ${jsonObj[key]}`);
          }
        
