# This is a basic workflow to help you get started with Actions

name: hello-github-actions

# Controls when the workflow will run
on:
  workflow_dispatch:
    inputs:
      json:
        type: string

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  job2:
    runs-on: ubuntu-latest
    steps:
      - id: parse_json
        run: |
          echo ${{ inputs.json }}
          echo ${{ toJson(inputs.json) }}
          for row in $(echo "${{ toJson(inputs.json) }}" | jq -c '.[]'); do
            name=$(echo "${row}" | jq -r '.source_repo')
            echo "Name: ${name}"
          done
