# This is a basic workflow to help you get started with Actions

name: hello-github-actions

# Controls when the workflow will run
on:
  workflow_dispatch:
    inputs:
      json:
        type: string

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  job1:
    uses: huatangli/hc-demo/.github/workflows/test.yml@main
  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - run: |
          echo ${{ inputs.str}}
          tags=$(echo "$json" | jq -rc '.[]')

          # 输出tag值
          for tag in $tags; do
              echo "Tag: $tag"
          done
