# This is a basic workflow to help you get started with Actions

name: hello-github-actions

# Controls when the workflow will run
on:
  workflow_dispatch:
    inputs:
      json:
        type: string

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  job2:
    runs-on: linux-fc
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run database migrations
        run: |
          pwd
