# This is a basic workflow to help you get started with Actions

name: hello-github-actions

# Controls when the workflow will run
on:
  workflow_dispatch:
    inputs:
      json:
        type: string

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  job2:
    runs-on: ubuntu-latest
    steps:
      - run: |
          import json
          echo "啊啊啊啊${{ inputs.json }}"
          
          # 将输入值转换为JSON对象
          input_json = json.loads(${{ inputs.json }})

          # 输出JSON对象的内容
          print("Input JSON:")
          print(json.dumps(input_json, indent=4))
        
