# This is a basic workflow to help you get started with Actions

name: hello-github-actions

# Controls when the workflow will run
on:
  workflow_dispatch:
    inputs:
      json:
        type: string

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  job2:
    runs-on: ubuntu-latest
    steps:
      - id: parse_json
        run: |
          echo ${{ inputs.json }}
          echo ${{ toJson(inputs.json) }}
          # for row in $(echo "${{ toJson(inputs.json) }}" | jq -rc '.[]'); do
           
          #   echo "Name: ${row}"
          # done
          lines=$(echo "${{ toJson(inputs.json) }}" | jq -r '.[] | @base64')

          # 使用for循环遍历每行数据
          for line in $lines; do
              # 解码base64编码的行数据
              decoded_line=$(echo "$line" | base64 --decode)
              # 输出解码后的数据
              echo "$decoded_line"
          done
