# This is a basic workflow to help you get started with Actions

name: hello-github-actions

# Controls when the workflow will run
on:
  workflow_dispatch:
    inputs:
      json:
        type: string

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  job2:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo ${{ inputs.str}}
          for obj in $(echo "$json" | jq -c '.[]'); do
            deploySeq=$(echo "$obj" | jq -r '.deploySeq')
            fallbackSeq=$(echo "$obj" | jq -r '.fallbackSeq')
            source_repo=$(echo "$obj" | jq -r '.source_repo')
            tag=$(echo "$obj" | jq -r '.tag')
            commitId=$(echo "$obj" | jq -r '.commitId')
        
            echo "deploySeq: $deploySeq"
            echo "fallbackSeq: $fallbackSeq"
            echo "source_repo: $source_repo"
            echo "tag: $tag"
            echo "commitId: $commitId"
            echo
          done
