# This is a basic workflow to help you get started with Actions

name: hello-github-actions

# Controls when the workflow will run
on:
  workflow_dispatch:
  repository_dispatch:
  workflow_run:
    workflows: ["blank"]
    types:
      - completed

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  job1:
    uses: huatangli/hc-demo/.github/workflows/test.yml@main
  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - run: |
          echo "Build result: ${{ needs.blank.outputs.firstword }}"
