# This is a basic workflow to help you get started with Actions

name: hello-github-actions

# Controls when the workflow will run
on:
  workflow_dispatch:
    inputs:
      json:
        type: string

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  job2:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: 11.0.1
          distribution: 'adopt'
      - name: Run database migrations
        run: |
          cd mmybatis-migrations-3.3.11/bin
          chmod +x migrate
          ./migrate -cp lib/mysql-connector-java-8.0.19.jar -c ./sit.properties up
