# This is a basic workflow to help you get started with Actions

name: hello-github-actions

# Controls when the workflow will run
on:
  workflow_dispatch:
    inputs:
      json:
        type: string

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  job2:
    runs-on: ubuntu-latest
    steps:
      - name: Parse JSON
        id: parse_json
        run: |
          echo "${{ github.event.inputs.json }}" > json_data.json
          echo "::set-output name=filename::json_data.json"

      - name: Iterate over JSON
        id: iterate_json
        run: |

          # Use jq to extract the sequences
          sequences=$(cat ${{ github.event.inputs.json }} | jq -r '.[]')

          # Loop over the sequences
          for sequence in $sequences; do
            deploySeq=$(echo $sequence | jq -r '.deploySeq')
            fallbackSeq=$(echo $sequence | jq -r '.fallbackSeq')

            echo "Deploy Sequence: $deploySeq"
            echo "Fallback Sequence: $fallbackSeq"

            # Add your logic here for each sequence
            # For example, you can perform actions based on the deploySeq and fallbackSeq values
          done
        
